// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCruQwatiStSP_GgsApDNtAKPWC_Eq4li8',
    appId: '1:890716548165:web:63afed55ef991c36d6472c',
    messagingSenderId: '890716548165',
    projectId: 'ticket-76425',
    authDomain: 'ticket-76425.firebaseapp.com',
    storageBucket: 'ticket-76425.firebasestorage.app',
    measurementId: 'G-RF4PDR1XLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcQkUBo3ATnjjhhqqbXr4_lNkgiSvFrk',
    appId: '1:890716548165:android:cb291c2e57685a15d6472c',
    messagingSenderId: '890716548165',
    projectId: 'ticket-76425',
    storageBucket: 'ticket-76425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8S5yTwJ95YMk7sT3gk8_x1TQMgs6_sVM',
    appId: '1:890716548165:ios:3a7ed42f492b53edd6472c',
    messagingSenderId: '890716548165',
    projectId: 'ticket-76425',
    storageBucket: 'ticket-76425.firebasestorage.app',
    iosBundleId: 'com.example.ticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8S5yTwJ95YMk7sT3gk8_x1TQMgs6_sVM',
    appId: '1:890716548165:ios:3a7ed42f492b53edd6472c',
    messagingSenderId: '890716548165',
    projectId: 'ticket-76425',
    storageBucket: 'ticket-76425.firebasestorage.app',
    iosBundleId: 'com.example.ticket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCruQwatiStSP_GgsApDNtAKPWC_Eq4li8',
    appId: '1:890716548165:web:2dcd579dbb81ed50d6472c',
    messagingSenderId: '890716548165',
    projectId: 'ticket-76425',
    authDomain: 'ticket-76425.firebaseapp.com',
    storageBucket: 'ticket-76425.firebasestorage.app',
    measurementId: 'G-FFYMDRFKE2',
  );
}
